[job]
dump_folder = "./outputs"
description = "DeepSeek-V3.2 671B model training"
print_config = true
custom_config_module = "torchtitan_npu.config.custom_config"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 1
enable_memory_snapshot = false
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 1
disable_color_printing = false
enable_tensorboard = false
save_tb_folder = "tb"
enable_wandb = false

[model]
name = "deepseek_v32"
flavor = "671B_debug_128die"
hf_assets_path = "/data/models/DeepSeek-V3.2-bf16"
#converters = ["npu_dsa", "npu_rms_norm", "npu_permute"]
converters = ["npu_dsa", "npu_rms_norm", "npu_permute", "npu_gmm", "npu_rope"]

[optimizer]
name = "AdamW"
lr = 1e-5
eps = 1e-6
weight_decay = 0.01
beta2 = 0.999
swap_optimizer = true   # swap optimizer between host and device to save device memory during training
swap_optimizer_times = 16

[lr_scheduler]
warmup_steps = 2_000  # lr scheduler warm up, normally 20% of the train steps
decay_ratio = 0.8  # lr scheduler decay ratio, 80% of the train steps
decay_type = "cosine"
min_lr_factor = 0.01

[training]
local_batch_size = 16
# global_batch_size = 32
seq_len = 32768
max_norm = 1.0  # grad norm clipping
steps = 10000
dataset = "enwiki-eod"  # supported datasets: c4_test (2K), c4 (177M) , enwiki-eod
dataset_path = "./tests/assets/enwiki"  # change to your dataset path

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
fsdp_reshard_after_forward = "always" # default / never / always
tensor_parallel_degree = 4
enable_async_tensor_parallel = false
pipeline_parallel_degree = 2
pipeline_parallel_schedule = "Interleaved1F1B"
expert_parallel_degree = 64
expert_tensor_parallel_degree = 1
context_parallel_degree = 16
enable_custom_context_parallel = true
custom_context_parallel_path = "torchtitan_npu.distributed.context_parallel.dsa_cp.AscendDSAContextParallelContext"

[checkpoint]
enable = true
folder = "checkpoint"
interval = 10000
last_save_model_only = true
export_dtype = "float32"
async_mode = "disabled"  # ["disabled", "async", "async_with_pinned_mem]"
initial_load_path = "/data/model/DeepSeek-V3.2-bf16"
initial_load_in_hf = true
# initial_load_in_hf_quantized = true
load_step = 0

[activation_checkpoint]
mode = "full"  # ["none", "selective", "full"]
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[compile]
enable = false
components = ["loss"] # ["model", "loss"]

[quantize.linear.float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false
filter_fqns = ["output", "router.gate"]

[quantize.grouped_mm.float8]
fqns = ["experts"]